### PR TITLE
Project improvements

### PR DESCRIPTION
**Pull request by williamdes**
I improved the README and made a slimmer Docker image

And made other improvements..
And made the README compliant with this tool: https://github.com/tianon/markdownfmt/pull/2/commits/7561261c954cd6d29c6b1004c34a2e815e97cb9a

Edit: Yes I know this is a fork but upstream seems abandoned, we should not care further

### CODE REVIEW

**Comment by williamdes** [comment]
CI passes !
https://github.com/williamdes/markdownfmt/runs/7766905751?check_suite_focus=true

Ready to merge

👀 **Next PR to be open after this one for GitHub actions format support:** https://github.com/williamdes/markdownfmt/pull/1 ◀️

**Comment by williamdes** [comment]
hi @tianon 
Are you notified about this repo ?

**Comment by tianon** [comment]
Yes, sorry - just haven't gotten around to reviewing this properly yet 🙈

**Comment by williamdes** [comment]
> Yes, sorry - just haven't gotten around to reviewing this properly yet 🙈

Haha no worries, if you are aware of the PR that's perfect my brain will stop reminding me of this subject 😄

**Comment by williamdes** [comment]
Hi @tianon
Some time passed since then, can you have a look to this one?

**Comment by williamdes** [comment]
Hi @tianon
Should I refresh this one a bit with new go updates?

**Comment by williamdes** [comment]
Hello @tianon 
Could you please have a look to this one, so I can delete my fork 🙏🏻

**Comment by williamdes** [comment]
Feel free to cherry pick all the work, it's yours now

**Pull request closed without merging**
